language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -q -e . --use-mirrors
  - pip install -q -r example_mc_project/requirements.txt
script: django-admin.py test localtv --settings=example_mc_project.settings