language: python
python:
  - "2.6"
  - "2.7"
env:
  - MC_PAYPAL_REAL=
  - MC_PAYPAL_REAL=yes
install:
  - pip install -q -e . --use-mirrors
  - pip install -q -r example_mc_project/requirements.txt
script: django-admin.py test localtv --settings=example_mc_project.settings