language: python
python:
  - "2.6"
  - "2.7"
env:
  -
  - MIGRATIONS=yes
  - SEARCH=elasticsearch
  - DB=mysql
  - DB=postgres
before_install:
  - test x$SEARCH == xelasticsearch && sudo service elasticsearch start && sleep 3 || true
install:
  - pip install -q -e . --use-mirrors
  - pip install -q --use-mirrors -r test_mc_project/requirements.txt
  - sh -c "if [ '$MIGRATIONS' = 'yes' ]; then pip install -q --use-mirrors south; fi"
  - sh -c "if [ '$SEARCH' = 'elasticsearch' ]; then pip install -q --use-mirrors pyelasticsearch; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then pip install -q --use-mirrors mysql-python; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then pip install -q --use-mirrors psycopg2; fi"
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE mirocommunity_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE mirocommunity_test;'; fi"
script:
  - test_mc_project/manage.py test localtv --verbosity=2
  - test_mc_project/manage.py test localtv.contrib.contests --verbosity=2
