language: python
python:
  - "2.6"
  - "2.7"
env:
  -
  - MIGRATIONS=yes
  - SEARCH=elasticsearch
  - DB=mysql
  - DB=postgres
before_install:
  - test x$SEARCH == xelasticsearch && sudo service elasticsearch start && sleep 3 || true
install:
  - pip install -q -e . --use-mirrors
  - pip install -q --use-mirrors -r test_mc_project/requirements.txt
  - test x$MIGRATIONS == xyes && pip install -q --use-mirrors south || true
  - test x$SEARCH == xelasticsearch && pip install -q pyelasticsearch || true
  - test x$DB == xmysql && pip install -q --use-mirrors mysql-python || true
  - test x$DB == xpostgres && pip install -q --use-mirrors psycopg2 || true
script:
  - test_mc_project/manage.py test localtv --verbosity=2
  - test_mc_project/manage.py test localtv.contrib.contests --verbosity=2
